/**
 * Copies the engine's report + Fix Assistant styles into the WordPress plugin, and packages the plugin as a zip:
 *   npm run build:wp
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { FIX_CSS } from '../src/fix/render.js';
import { REPORT_CSS } from '../src/report/render.js';

const pluginDir = path.resolve('wordpress-plugin/website-investigator');
const css = `/* Generated by npm run build:wp from the engine — do not edit. */\n${REPORT_CSS}\n${FIX_CSS}\n`;
fs.writeFileSync(path.join(pluginDir, 'assets', 'engine.css'), css);
console.log('Wrote assets/engine.css');

const zip = path.resolve('wordpress-plugin/website-investigator.zip');
fs.rmSync(zip, { force: true });
try {
  // bsdtar writes zip archives with -a. Windows ships it in System32 (Git Bash's GNU tar cannot write zips);
  // relative paths avoid drive-letter parsing.
  const tar = process.platform === 'win32' ? path.join(process.env.SystemRoot ?? 'C:\\Windows', 'System32', 'tar.exe') : 'tar';
  execFileSync(tar, ['-a', '-c', '-f', path.basename(zip), 'website-investigator'], { cwd: path.dirname(pluginDir) });
  console.log(`Packaged ${zip}`);
} catch (e) {
  console.warn(`Could not create the zip automatically (${(e as Error).message}). Zip the folder wordpress-plugin/website-investigator manually.`);
}
